# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1273, 503)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 1271, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(203, 350, 791, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.chromeDriverDirLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.chromeDriverDirLineEdit.setObjectName("chromeDriverDirLineEdit")
        self.horizontalLayout_5.addWidget(self.chromeDriverDirLineEdit)
        self.setDriverDirBt = QtWidgets.QPushButton(self.layoutWidget)
        self.setDriverDirBt.setObjectName("setDriverDirBt")
        self.horizontalLayout_5.addWidget(self.setDriverDirBt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.logDirLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.logDirLineEdit.setObjectName("logDirLineEdit")
        self.horizontalLayout_3.addWidget(self.logDirLineEdit)
        self.setLogDirBt = QtWidgets.QPushButton(self.layoutWidget)
        self.setLogDirBt.setObjectName("setLogDirBt")
        self.horizontalLayout_3.addWidget(self.setLogDirBt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.reportLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.reportLineEdit.setObjectName("reportLineEdit")
        self.horizontalLayout_6.addWidget(self.reportLineEdit)
        self.setRrportDirBt = QtWidgets.QPushButton(self.layoutWidget)
        self.setRrportDirBt.setObjectName("setRrportDirBt")
        self.horizontalLayout_6.addWidget(self.setRrportDirBt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.online_device_Edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.online_device_Edit.setObjectName("online_device_Edit")
        self.horizontalLayout_4.addWidget(self.online_device_Edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.test_num_Edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.test_num_Edit.setObjectName("test_num_Edit")
        self.horizontalLayout_2.addWidget(self.test_num_Edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.startBt = QtWidgets.QPushButton(self.layoutWidget)
        self.startBt.setObjectName("startBt")
        self.horizontalLayout_7.addWidget(self.startBt)
        self.stopBt = QtWidgets.QPushButton(self.layoutWidget)
        self.stopBt.setObjectName("stopBt")
        self.horizontalLayout_7.addWidget(self.stopBt)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pa_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.pa_checkBox.setObjectName("pa_checkBox")
        self.horizontalLayout.addWidget(self.pa_checkBox)
        self.pa_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pa_pushButton.setObjectName("pa_pushButton")
        self.horizontalLayout.addWidget(self.pa_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.SelectAllpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.SelectAllpushButton.setObjectName("SelectAllpushButton")
        self.horizontalLayout_9.addWidget(self.SelectAllpushButton)
        self.refreshBt = QtWidgets.QPushButton(self.layoutWidget)
        self.refreshBt.setObjectName("refreshBt")
        self.horizontalLayout_9.addWidget(self.refreshBt)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(690, 330, 121, 20))
        self.timeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.timeEdit.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.timeEdit.setObjectName("timeEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 331, 48, 16))
        self.label_6.setObjectName("label_6")
        self.lineEditDay = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDay.setGeometry(QtCore.QRect(620, 330, 51, 20))
        self.lineEditDay.setObjectName("lineEditDay")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(675, 330, 16, 21))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动化测试"))
        self.label_5.setText(_translate("MainWindow", "chrome浏览器驱动路径"))
        self.setDriverDirBt.setText(_translate("MainWindow", "选择驱动路径"))
        self.label.setText(_translate("MainWindow", "日志"))
        self.setLogDirBt.setText(_translate("MainWindow", "设置日志路径"))
        self.label_2.setText(_translate("MainWindow", "报告"))
        self.setRrportDirBt.setText(_translate("MainWindow", "设置报告路径"))
        self.label_4.setText(_translate("MainWindow", "在线设备数"))
        self.label_3.setText(_translate("MainWindow", "测试次数："))
        self.startBt.setText(_translate("MainWindow", "开始"))
        self.stopBt.setText(_translate("MainWindow", "停止"))
        self.pa_checkBox.setText(_translate("MainWindow", "开启功放"))
        self.pa_pushButton.setText(_translate("MainWindow", "功放开关"))
        self.SelectAllpushButton.setText(_translate("MainWindow", "全选"))
        self.refreshBt.setText(_translate("MainWindow", "刷新配置"))
        self.label_6.setText(_translate("MainWindow", "倒计时："))
        self.label_7.setText(_translate("MainWindow", "天"))
